# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'NEInterview' do
  workspace './NEInterview.xcworkspace'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NEVCESDKDeps', :path => '../NEVCESDK'

  pod 'Masonry', '~> 1.1.0'
  pod 'Toast'
  pod 'YYModel'
  pod 'Reachability', '~> 3.2'
  pod 'NELog', '~> 0.0.1'
  pod 'NEScreenShareBroadcaster', '0.0.7'
  # pod 'Bugly'

# 活体检测界面
pod 'WHToast'
pod 'NTESLiveDetect', '3.0.3'
pod 'AFNetworking'
pod 'MBProgressHUD'
  
end